Repository pygments/pygments, pull requests merged in 2019-11, with the labels that each got.

#1259 Treat Skylark/Starlark files as Python
  pygments/lexers/_mapping.py
  pygments/lexers/python.py
Labels: enhancement

#1268 Add Lexer for scdoc
  pygments/lexers/_mapping.py
  pygments/lexers/scdoc.py
  tests/examplefiles/scdoc_manual.scd
Labels: enhancement

#1261 Update Logtalk lexer for the latest language specification
  pygments/lexers/prolog.py
Labels: T-feature

#1283 Exclude tests from distribution -- fix #1280
  setup.py
Labels: S-major, T-bug
