Repository pygments/pygments, pull requests merged in 2021-11, with the labels that each got.

#1924 Creating one dark style
  pygments/styles/onedark.py
Labels: theming, update needed

#1845 Add lexer and style for LilyPond
  AUTHORS
  doc/languages.rst
  external/lilypond-builtins-generator.ly
  pygments/lexers/_lilypond_builtins.py
  pygments/lexers/_mapping.py
  pygments/lexers/lilypond.py
  pygments/lexers/lisp.py
  pygments/styles/lilypond.py
  tests/examplefiles/lilypond/example.ly
  tests/examplefiles/lilypond/example.ly.output
Labels: lexing

#1968 Fixes for LilyPond
  doc/conf.py
  doc/languages.rst
  external/lilypond-builtins-generator.ly
  pygments/lexers/_lilypond_builtins.py
  pygments/style.py
  pygments/styles/lilypond.py
Labels: changelog-update

#1974 New lexer for Sophia contracts
  pygments/lexers/_mapping.py
  pygments/lexers/sophia.py
  tests/examplefiles/sophia/test.aes
  tests/examplefiles/sophia/test.aes.output
Labels: changelog-update
