Repository pygments/pygments, pull requests merged in 2021-04, with the labels that each got.

#1564 Fix #1416: add WebAssembly lexer
  pygments/lexers/_mapping.py
  pygments/lexers/webassembly.py
  tests/examplefiles/wat/fib.wat
  tests/examplefiles/wat/fib.wat.output
  tests/snippets/wat/test_align_and_offset_accept_hexadecimal_numbers.txt
  tests/snippets/wat/test_comment_with_open_paren.txt
  tests/snippets/wat/test_comment_with_semicolon.txt
  tests/snippets/wat/test_i32_const_is_builtin.txt
  tests/snippets/wat/test_multiline_comment.txt
  tests/snippets/wat/test_nested_comment.txt
  tests/snippets/wat/test_string_byte_escape.txt
  tests/snippets/wat/test_string_with_escape.txt
  tests/snippets/wat/test_variable_name_pattern.txt
Labels: update needed

#1768 Fix python lexer parsing floats incorrectly
  pygments/lexers/python.py
  tests/snippets/python/test_floats.txt
Labels: changelog-update

#1775 AMDGPU: Updated modifier tokenization.
  pygments/lexers/amdgpu.py
  tests/examplefiles/amdgpu/amdgpu.isa
  tests/examplefiles/amdgpu/amdgpu.isa.output
Labels: lexing

#1779 native: darker line numbers
  pygments/styles/native.py
Labels: changelog-update

#1780 uniformize aliases order
  doc/docs/lexers.rst
  pygments/lexers/_mapping.py
  pygments/lexers/actionscript.py
  pygments/lexers/ambient.py
  pygments/lexers/automation.py
  pygments/lexers/bibtex.py
  pygments/lexers/configs.py
  pygments/lexers/graphics.py
  pygments/lexers/haskell.py
  pygments/lexers/haxe.py
  pygments/lexers/installers.py
  pygments/lexers/javascript.py
  pygments/lexers/lisp.py
  pygments/lexers/markup.py
  pygments/lexers/ml.py
  pygments/lexers/nimrod.py
  pygments/lexers/parsers.py
  pygments/lexers/resource.py
  pygments/lexers/rnc.py
  pygments/lexers/ruby.py
  pygments/lexers/scripting.py
  pygments/lexers/shell.py
  pygments/lexers/supercollider.py
  pygments/lexers/templates.py
  pygments/lexers/teraterm.py
  pygments/lexers/testing.py
  pygments/lexers/trafficscript.py
Labels: changelog-update, update needed
