Repository pygments/pygments, pull requests merged in 2022-03, with the labels that each got.

#2040 Add UL4 lexer.
  AUTHORS
  doc/languages.rst
  pygments/lexers/_mapping.py
  pygments/lexers/ul4.py
  tests/examplefiles/ul4/example_operators.ul4
  tests/examplefiles/ul4/example_operators.ul4.output
  tests/examplefiles/ul4/example_tags.ul4
  tests/examplefiles/ul4/example_tags.ul4.output
  tests/examplefiles/ul4/example_template.ul4
  tests/examplefiles/ul4/example_template.ul4.output
  tests/examplefiles/ul4/example_types.ul4
  tests/examplefiles/ul4/example_types.ul4.output
Labels: update needed

#2084 CFamily: Lex identifiers after `case` as constants
  pygments/lexers/c_cpp.py
  tests/examplefiles/c/ceval.c.output
  tests/examplefiles/c/example.c.output
  tests/examplefiles/c/labels.c
  tests/examplefiles/c/labels.c.output
  tests/examplefiles/ec/test.ec.output
  tests/examplefiles/nesc/IPDispatchP.nc.output
  tests/examplefiles/pike/FakeFile.pike.output
  tests/examplefiles/ragel-cpp/ragel-cpp_rlscan.output
  tests/snippets/c/test_switch.txt
  tests/snippets/c/test_switch_space_before_colon.txt
Labels: changelog-update

#2097 Terraform: Fix class name lexing
  pygments/lexers/configs.py
  tests/snippets/terraform/test_backend.txt
  tests/snippets/terraform/test_comment.txt
  tests/snippets/terraform/test_functions.txt
  tests/snippets/terraform/test_heredoc.txt
  tests/snippets/terraform/test_module.txt
  tests/snippets/terraform/test_resource.txt
  tests/snippets/terraform/test_types.txt
  tests/snippets/terraform/test_variable_declaration.txt
  tests/snippets/terraform/test_variable_read.txt
Labels: changelog-update

#1791 Add Macaulay2 lexer
  AUTHORS
  pygments/lexers/_mapping.py
  pygments/lexers/macaulay2.py
  tests/examplefiles/macaulay2/test.m2
  tests/examplefiles/macaulay2/test.m2.output
Labels: lexing, changelog-update
