Repository pygments/pygments, pull requests merged in 2022-01, with the labels that each got.

#2018 Java: fix lexing of 'record' soft keyword
  pygments/lexers/jvm.py
  tests/snippets/java/test_record.txt
Labels: lexing

#2022 CFamily: improve label detection
  pygments/lexers/c_cpp.py
  tests/examplefiles/c/ceval.c.output
  tests/examplefiles/c/example.c.output
  tests/examplefiles/c/labels.c
  tests/examplefiles/c/labels.c.output
  tests/examplefiles/charmci/Charmci.ci.output
  tests/examplefiles/ec/test.ec.output
  tests/examplefiles/objective-c/objc_example.m.output
  tests/examplefiles/swig/swig_java.swg.output
Labels: lexing

#2038 Native: adjust colours to meet WCAG AAA contrast guidelines
  pygments/styles/native.py
Labels: changelog-update, theming

#2042 Highlight Clojure ratios as Numbers
  pygments/lexers/jvm.py
Labels: changelog-update

#2026 Use `linespans` for `anchorlinenos`
  pygments/formatters/html.py
  tests/test_html_formatter.py
Labels: formatting, changelog-update
